Improve and fail-safe icinga2 interaction

diff --git a/debian/icinga-web-config-icinga2-ido-mysql.postinst b/debian/icinga-web-config-icinga2-ido-mysql.postinst
--- a/debian/icinga-web-config-icinga2-ido-mysql.postinst
+++ b/debian/icinga-web-config-icinga2-ido-mysql.postinst
@@ -30,14 +30,25 @@ is_fresh_install()
 enable_icinga2_commandpipe() {
     if is_fresh_install $@; then
         echo "enabling icinga2 features for classicui"
-        if [ -e "/usr/sbin/icinga2-enable-feature" ] 
+        if [   -e "/etc/icinga2/features-available/command.conf" ] &&
+           [ ! -e "/etc/icinga2/features-enabled/command.conf" ]
         then
-            icinga2-enable-feature command
-        else
-            icinga2 feature enable command
+            do_reload=0
+            if [ -x "/usr/sbin/icinga2-enable-feature" ]; then
+                if icinga2-enable-feature command; then
+                    do_reload=1
+                fi
+            elif [ -x "/usr/sbin/icinga2" ]; then
+                if icinga2 feature enable command; then
+                    do_reload=1
+                fi
+            fi
+
+            if [ "$do_reload" = "1" ]; then
+                echo "reloading icinga2"
+                [ -x $(which invoke-rc.d) ] && invoke-rc.d icinga2 reload || true
+            fi
         fi
-        echo "reloading icinga2"
-        [ -x $(which invoke-rc.d) ] && invoke-rc.d icinga2 reload
     fi
 }
 
@@ -71,7 +82,7 @@ generate_dbxml() {
 
     # leave when dbconfig not enabled
     if [ "$dbc_install" != "true" ]; then
-        echo "database config failed: dbconfig-common for \"$(basename $dbconfig .conf)\" not enabled!" 
+        echo "database config failed: dbconfig-common for \"$(basename $dbconfig .conf)\" not enabled!"
         exit 1
     fi
 
